=== kryuki/msys64/msys64/home/kobay/qmk_utils/flip/bin/GuiDescriptionFiles/gui.dtd
<!--

      ======================================
      DTD for Flip XML Gui Description Files
      ======================================

-->

<!ELEMENT Gui (JPanel | Separator)*>

<!ELEMENT JPanel (LayoutManager | JPanel | Border | JButton | JRadioButton | JLabel | JFormattedTextField | Separator | JTextField | JCheckBox | HorizontalStrut | VerticalStrut | JComboBox | JSpinner)+>
<!ATTLIST JPanel NAME CDATA #IMPLIED>

<!ELEMENT Separator EMPTY>
<!ATTLIST Separator
    ORIENTATION CDATA #IMPLIED>
    
<!ELEMENT LayoutManager EMPTY>
<!ATTLIST LayoutManager
    NAME  (BoxLayout | FlowLayout) #REQUIRED
    AXIS  (BoxLayout.X_AXIS | BoxLayout.Y_AXIS) #IMPLIED
    ALIGN (FlowLayout.LEFT | FlowLayout.CENTER | FlowLayout.RIGHT) #IMPLIED
    HGAP  CDATA #IMPLIED
    VGAP  CDATA #IMPLIED>

<!ELEMENT	Border EMPTY>
<!ATTLIST	Border
    TYPE	(LoweredBevel | RaisedBevel | Titled) #REQUIRED
    TITLE	CDATA	#IMPLIED>

<!ELEMENT JButton EMPTY>
<!ATTLIST JButton
	NAME			CDATA #REQUIRED
    TEXT			CDATA #REQUIRED
    HANDLER			CDATA #REQUIRED
    TOOLTIP			CDATA #IMPLIED
    TOOLTIP_IMAGE	CDATA #IMPLIED
    BCOLOR			CDATA #IMPLIED
    FCOLOR			CDATA #IMPLIED>

<!ELEMENT JRadioButton EMPTY>
<!ATTLIST JRadioButton
    NAME    CDATA #REQUIRED
    TEXT    CDATA #REQUIRED
    HANDLER CDATA #REQUIRED>

<!ELEMENT JLabel EMPTY>
<!ATTLIST JLabel
    TEXT CDATA #REQUIRED>

<!ELEMENT JFormattedTextField EMPTY>
<!ATTLIST JFormattedTextField
    NAME			CDATA #REQUIRED
    COLUMNS			CDATA #REQUIRED
    HANDLER			CDATA #REQUIRED
    TEXT			CDATA #IMPLIED
    TOOLTIP			CDATA #IMPLIED
    TOOLTIP_IMAGE	CDATA #IMPLIED
    EDITABLE		(true | false) "true">

<!ELEMENT JTextField EMPTY>
<!ATTLIST JTextField
    NAME			CDATA #REQUIRED
    COLUMNS			CDATA #REQUIRED
    HANDLER			CDATA #REQUIRED
    TEXT			CDATA #IMPLIED
    TOOLTIP			CDATA #IMPLIED
    TOOLTIP_IMAGE	CDATA #IMPLIED
    EDITABLE		(true | false) "true">

<!ELEMENT JCheckBox EMPTY>
<!ATTLIST JCheckBox 
    NAME			CDATA #REQUIRED
    TEXT			CDATA #REQUIRED
    HANDLER			CDATA #REQUIRED
    SELECTED		(true | false) "false"
    TOOLTIP			CDATA #IMPLIED
    TOOLTIP_IMAGE	CDATA #IMPLIED>

<!ELEMENT HorizontalStrut EMPTY>
<!ATTLIST HorizontalStrut
    WIDTH CDATA #REQUIRED>

<!ELEMENT VerticalStrut EMPTY>
<!ATTLIST VerticalStrut
    HEIGHT CDATA #REQUIRED>

<!ELEMENT JSpinner EMPTY>
<!ATTLIST JSpinner
    NAME			CDATA #REQUIRED
    VALUES			CDATA #REQUIRED
    HANDLER			CDATA #REQUIRED
    TOOLTIP			CDATA #IMPLIED
    TOOLTIP_IMAGE	CDATA #IMPLIED>

<!ELEMENT JComboBox EMPTY>
<!ATTLIST JComboBox
    NAME			CDATA #REQUIRED
    VALUES			CDATA #REQUIRED
    HANDLER			CDATA #REQUIRED
    TOOLTIP			CDATA #IMPLIED
    TOOLTIP_IMAGE	CDATA #IMPLIED>

=== kryuki/msys64/msys64/home/kobay/qmk_utils/flip/bin/GuiDescriptionFiles/at89c51rb2_gui.xml
<?xml version="1.0"?>
<!DOCTYPE Gui SYSTEM "gui.dtd">
<Gui>
   <JPanel NAME="ReadOnlyBytes">
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="5" />

         <JLabel TEXT="Signature Bytes" />

         <JFormattedTextField NAME="manuf_id" COLUMNS="2" TOOLTIP="Manufacturer ID" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="family_code_id" COLUMNS="2" TOOLTIP="Family Code" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_name_id" COLUMNS="2" TOOLTIP="Device Name" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_rev_id" COLUMNS="2" TOOLTIP="Device Revision" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="1" />

         <JLabel TEXT="Device Boot Ids" />

         <JFormattedTextField NAME="device_boot_id_1" COLUMNS="2" TOOLTIP="Boot ID 1" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_boot_id_2" COLUMNS="2" TOOLTIP="Boot ID 2" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="1" />

         <JLabel TEXT="Hardware Byte " />

         <JFormattedTextField NAME="hardware_byte" COLUMNS="2" HANDLER="com.atmel.flip.HwbByteHandler" EDITABLE="false" />

         <JCheckBox NAME="hardware_byte_6" TEXT="BLJB" TOOLTIP="Bootloader Jump Bit" HANDLER="com.atmel.flip.HwbCheckBoxHandler_1" />

         <JCheckBox NAME="hardware_byte_7" TEXT="X2" TOOLTIP="X2 Bit Mode" HANDLER="com.atmel.flip.HwbCheckBoxHandler_1" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="1" />

         <JLabel TEXT="Bootloader Ver. " />

         <JTextField NAME="boot_loader_version" COLUMNS="4" TOOLTIP="Bootloader Version" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>
   </JPanel>

   <Separator />

   <JPanel NAME="bsb_sbv">
      <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="5" />

      <JLabel TEXT="BSB / SBV " />

      <JFormattedTextField NAME="bsb" TEXT="XX" COLUMNS="2" TOOLTIP="Boot Status Byte" HANDLER="com.atmel.flip.BsbByteHandler" />

      <JFormattedTextField NAME="sbv" TEXT="XX" COLUMNS="2" TOOLTIP="Software Boot Vector" HANDLER="com.atmel.flip.SbvByteHandler" />
   </JPanel>

   <Separator />

   <JPanel>
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="5" />

         <JLabel TEXT="Security Level" />

         <JTextField NAME="ssb" COLUMNS="2" TOOLTIP="Software Security Byte" HANDLER="com.atmel.flip.SsbByteHandler" EDITABLE="false" />
      </JPanel>

      <JPanel NAME="security">
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" />

         <JRadioButton NAME="lev0" TEXT="Level 0" HANDLER="com.atmel.flip.SsbRadioButtonHandler_1" />

         <JRadioButton NAME="lev1" TEXT="Level 1" HANDLER="com.atmel.flip.SsbRadioButtonHandler_1" />

         <JRadioButton NAME="lev2" TEXT="Level 2" HANDLER="com.atmel.flip.SsbRadioButtonHandler_1" />
      </JPanel>
   </JPanel>

   <Separator />

   <JPanel NAME="startAppli">
      <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="5" VGAP="5" />

      <JButton NAME="start_appli" TEXT="Start Application" BCOLOR="orange" HANDLER="com.atmel.flip.StartAppliButtonHandler" />

      <JCheckBox NAME="Reset" TEXT="Reset" TOOLTIP="Generates a Wadtchdog Reset Pulse" HANDLER="com.atmel.flip.StartAppliResetCheckBoxHandler" />
   </JPanel>
</Gui>

=== kryuki/msys64/msys64/home/kobay/qmk_utils/flip/bin/GuiDescriptionFiles/at90canxx_gui.xml
<?xml version="1.0"?>
<!DOCTYPE Gui SYSTEM "gui.dtd">
<Gui>
   <JPanel NAME="ReadOnlyBytes">
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="5" />

         <JLabel TEXT="Signature Bytes" />

         <JFormattedTextField NAME="manuf_id" COLUMNS="2" TOOLTIP="Manufacturer ID" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="family_code_id" COLUMNS="2" TOOLTIP="Family Code" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_name_id" COLUMNS="2" TOOLTIP="Device Name" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_rev_id" COLUMNS="2" TOOLTIP="Device Revision" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="0" />

         <JLabel TEXT="Bootloader Ver." />

         <JTextField NAME="boot_loader_version" COLUMNS="4" TOOLTIP="Bootloader Version" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>
   </JPanel>

   <Separator />

   <JPanel NAME="CANPANEL">
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="5" />

         <JLabel TEXT="CANBT Registers" />

         <JFormattedTextField NAME="cbtr1" COLUMNS="2" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="cbtr2" COLUMNS="2" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="cbtr3" COLUMNS="2" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.CENTER" HGAP="2" VGAP="5" />

         <JButton NAME="can" TEXT="CAN" TOOLTIP="Set CAN Node Parameters" HANDLER="com.atmel.flip.CanButtonHandler" />
      </JPanel>
   </JPanel>

   <Separator />

   <JPanel NAME="bsb_eb">
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="2" />

         <JLabel TEXT="Bootloader Parameters" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="0" />

         <JLabel TEXT="Boot Status Byte" />

         <JFormattedTextField NAME="BSB" COLUMNS="2" TOOLTIP_IMAGE="bsb_flow.gif" HANDLER="com.atmel.flip.ByteHandler" />

         <HorizontalStrut WIDTH="20" />

         <JLabel TEXT="Extra Byte" />

         <JFormattedTextField NAME="EB" COLUMNS="2" TOOLTIP="Use auto-bitrate if 0xFF" HANDLER="com.atmel.flip.ByteHandler" />
      </JPanel>
   </JPanel>

   <Separator />

   <JPanel NAME="SoftwareSecurityLevel">
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="5" />

         <JLabel TEXT="Software Security Level" />

         <JFormattedTextField NAME="ssb" COLUMNS="2" TOOLTIP="Software Security Byte" HANDLER="com.atmel.flip.SsbByteHandler" EDITABLE="false" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="2" />

         <JRadioButton NAME="lev0" TEXT="Level 0" HANDLER="com.atmel.flip.SsbRadioButtonHandler_2" />

         <JRadioButton NAME="lev1" TEXT="Level 1" HANDLER="com.atmel.flip.SsbRadioButtonHandler_2" />

         <JRadioButton NAME="lev2" TEXT="Level 2" HANDLER="com.atmel.flip.SsbRadioButtonHandler_2" />
      </JPanel>
   </JPanel>

   <Separator />

   <JPanel NAME="StartAppli">
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="5" />

         <JLabel TEXT="Start Word-Address" />

         <JFormattedTextField NAME="SA_H" COLUMNS="2" TOOLTIP="Start Application MSB" HANDLER="com.atmel.flip.ByteHandler" />

         <JFormattedTextField NAME="SA_L" COLUMNS="2" TOOLTIP="Start Application LSB" HANDLER="com.atmel.flip.ByteHandler" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="5" VGAP="0" />

         <JButton NAME="RESET" TEXT="Reset" BCOLOR="green" TOOLTIP="Generates a hardware reset" HANDLER="com.atmel.flip.StartAppliButtonHandler" />

         <JLabel TEXT=" " />

         <JButton NAME="SA_ADD" TEXT="Start Application" BCOLOR="orange" TOOLTIP="Jump to the above defined word-address (Application)" HANDLER="com.atmel.flip.StartAppliButtonHandler" />
      </JPanel>
   </JPanel>
</Gui>

=== kryuki/msys64/msys64/home/kobay/qmk_utils/flip/bin/GuiDescriptionFiles/at89c51re2_gui.xml
<?xml version="1.0"?>
<!DOCTYPE Gui SYSTEM "gui.dtd">
<Gui>
   <JPanel NAME="ReadOnlyBytes">
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="5" />

         <JLabel TEXT="Signature Bytes" />

         <JFormattedTextField NAME="manuf_id" COLUMNS="2" TOOLTIP="Manufacturer ID" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="family_code_id" COLUMNS="2" TOOLTIP="Family Code" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_name_id" COLUMNS="2" TOOLTIP="Device Name" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_rev_id" COLUMNS="2" TOOLTIP="Device Revision" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="1" />

         <JLabel TEXT="Device Boot Ids" />

         <JFormattedTextField NAME="device_boot_id_1" COLUMNS="2" TOOLTIP="Boot ID 1" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_boot_id_2" COLUMNS="2" TOOLTIP="Boot ID 2" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="1" />

         <JLabel TEXT="Bootloader Ver. " />

         <JTextField NAME="boot_loader_version" COLUMNS="4" TOOLTIP="Bootloader Version" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>
   </JPanel>

   <Separator />

   <JPanel NAME="FcbBrv">
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="10" />

         <JLabel TEXT="FCB" />

         <JFormattedTextField NAME="fcb" COLUMNS="2" TOOLTIP="Fuses Configuration Byte" HANDLER="com.atmel.flip.FcbByteHandler" EDITABLE="false" />

         <HorizontalStrut WIDTH="10" />

         <JCheckBox NAME="fcb_7" TEXT="X2" TOOLTIP="X2 Bit Mode" HANDLER="com.atmel.flip.FcbCheckBoxHandler" />

         <HorizontalStrut WIDTH="10" />

         <JLabel TEXT="BRV" />

         <JComboBox NAME="brv" VALUES="0,1,2,3,4,5,6,7" TOOLTIP="Boot Reset Vector" HANDLER="com.atmel.flip.BrvComboHandler" />
      </JPanel>
   </JPanel>

   <Separator />

   <JPanel>
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel NAME="security">
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="10" />

         <HorizontalStrut WIDTH="10" />

         <JLabel TEXT="Flash Security Level" />

         <JComboBox NAME="flash_security" VALUES="0,1,2,3" TOOLTIP="Flash Security Level" HANDLER="com.atmel.flip.FlashSecurityComboHandler" />

         <HorizontalStrut WIDTH="10" />
      </JPanel>
   </JPanel>

   <Separator />

   <JPanel NAME="startAppliSingle">
      <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.CENTER" HGAP="5" VGAP="10" />

      <JButton NAME="start_appli" TEXT="Start Application" BCOLOR="orange" HANDLER="com.atmel.flip.StartAppliButtonHandler" />
   </JPanel>
</Gui>

=== kryuki/msys64/msys64/home/kobay/qmk_utils/flip/bin/GuiDescriptionFiles/at90usb1287_gui.xml
<?xml version="1.0"?>
<!DOCTYPE Gui SYSTEM "gui.dtd">
<Gui>
   <JPanel NAME="ReadOnlyBytes">
      <LayoutManager NAME="BoxLayout" AXIS="BoxLayout.Y_AXIS" />

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="5" />

         <JLabel TEXT="Signature Bytes" />

         <JFormattedTextField NAME="manuf_id" COLUMNS="2" TOOLTIP="Manufacturer ID" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="family_code_id" COLUMNS="2" TOOLTIP="Family Code" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_name_id" COLUMNS="2" TOOLTIP="Device Name" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_rev_id" COLUMNS="2" TOOLTIP="Device Revision" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="1" />

         <JLabel TEXT="Device Boot Ids" />

         <JFormattedTextField NAME="device_boot_id_1" COLUMNS="2" TOOLTIP="Boot ID 1" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />

         <JFormattedTextField NAME="device_boot_id_2" COLUMNS="2" TOOLTIP="Boot ID 2" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>

      <JPanel>
         <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="2" VGAP="1" />

         <JLabel TEXT="Bootloader Ver. " />

         <JTextField NAME="boot_loader_version" COLUMNS="4" TOOLTIP="Bootloader Version" HANDLER="com.atmel.flip.ByteHandler" EDITABLE="false" />
      </JPanel>

      <VerticalStrut HEIGHT="130" />
   </JPanel>

   <Separator />

   <JPanel NAME="startAppli">
      <LayoutManager NAME="FlowLayout" ALIGN="FlowLayout.LEFT" HGAP="5" VGAP="5" />

      <JButton NAME="start_appli" TEXT="Start Application" BCOLOR="orange" HANDLER="com.atmel.flip.StartAppliButtonHandler" />

      <JCheckBox NAME="Reset" TEXT="Reset" TOOLTIP="Generates a Wadtchdog Reset Pulse" SELECTED="true" HANDLER="com.atmel.flip.StartAppliResetCheckBoxHandler" />
   </JPanel>
</Gui>
